#!/usr/bin/env bash
# @testcase: usage-netpbm-r21-pnmtopng-text-keyword-comment-chunk
# @title: netpbm pnmtopng -text writes a tEXt chunk with the Comment keyword
# @description: Writes a tEXt directive file via pnmtopng -text and asserts the produced PNG byte stream literally contains the tEXt chunk type and the Comment keyword string, pinning libpng's tEXt chunk emission through the netpbm encoder.
# @timeout: 120
# @tags: usage, png, netpbm, pnmtopng, text-chunk, r21
# @client: netpbm

set -euo pipefail
source /validator/tests/_shared/runtime_helpers.sh

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

python3 - "$tmpdir/in.ppm" <<'PY'
import sys
W, H = 4, 4
body = bytearray()
for y in range(H):
    for x in range(W):
        body += bytes((x * 60 % 256, y * 60 % 256, 32))
open(sys.argv[1], 'wb').write(f'P6\n{W} {H}\n255\n'.encode() + body)
PY

cat >"$tmpdir/text.txt" <<'TXT'
Comment Generated by netpbm r21 test
TXT

pnmtopng -text "$tmpdir/text.txt" "$tmpdir/in.ppm" >"$tmpdir/out.png"
python3 - "$tmpdir/out.png" <<'PY'
import sys
data = open(sys.argv[1], 'rb').read()
assert data[:8] == b'\x89PNG\r\n\x1a\n'
assert b'tEXt' in data
assert b'Comment' in data
PY
