# Open Watcom makefile to build SDL2 tests for Win32
# wmake -f Makefile.w32
#
# To error out upon warnings: wmake -f Makefile.w32 ENABLE_WERROR=1

SYSTEM = nt

INCPATH = -I"$(%WATCOM)/h/nt" -I"$(%WATCOM)/h"

VULKAN_TEST =
VULKAN_TEST_CFLAGS =
!ifdef VULKAN_SDK
INCPATH += -I"$(VULKAN_SDK)\Include"
VULKAN_TEST = testvulkan.exe
VULKAN_TEST_CFLAGS = -DSDL_PUBLIC_VULKAN_HEADER=\"vulkan/vulkan.h\"
!endif

CFLAGS = -bt=nt -d0 -q -bm -5s -fp5 -fpi87 -sg -oteanbmier -ei
CFLAGS+= -wx -wcd=303
!ifeq ENABLE_WERROR 1
CFLAGS+= -we
!endif
CFLAGS+= -DSDL_MAIN_HANDLED
CFLAGS+= -DHAVE_OPENGL -DHAVE_SIGNAL_H
GLLIBS = opengl32.lib

TNSRCS = testnative.c testnativew32.c

!include watcom.mif
